lukso-network/universalprofile-test-dapp

src/components/endpoints/Sign.vue, src/components/endpoints/__tests__/Sign.ts
This PR fixes an error that was occurring when you try to validate a message against a signature. The RPC node returns a `err: insufficient funds for gas * price + value: ...` error. After some investigation, it was discovered it's a recent behavior with L16 nodes (where passing an explicit `gasPrice` causes a call to a `view` function to fail). The fix here applies only for the special case of `signature validation` while we continue to investigate what has changed at the network level
Details: https://app.clickup.com/t/2jzquwd
=> fix: insufficient funds for gas error when validating signature on UP contract

package-lock.json, src/components/Connect.vue, src/components/endpoints/Accounts.vue, src/compositions/useWalletConnect.ts
After migration to Vite, the dist build was not working properly when importing WalletConnect lib.
I've disabled it so we can deploy this version on GitHub Pages.
We will soon migrate to WalletConnect2
https://app.clickup.com/t/2tt91az
-> Will merge now without approval to finalise the deployment - we can adjust stuff tmrw if needed.
=> Temporary disable WalletConnect

src/components/__tests__/Connect.spec.ts, src/components/endpoints/__tests__/Accounts.spec.ts
We will enable this again when setting up WC2.
The previous PR failed tests: https://github.com/lukso-network/universalprofile-test-dapp/pull/53
I've added required status check so this will not happen anymore.
=> Disable WC related tests

src/components/endpoints/CustomRelayer.vue
Adding some default values just for convenience in testing custom relayers
=> fix: add default values to custom relayer

src/components/endpoints/Sign.vue, src/components/endpoints/__tests__/Sign.spec.ts
https://app.clickup.com/t/2tfghry
Since date params are optional there should be a way to disable them and not pass in the message. This will allow to test "default" 2min expiry time which ext will add in case of missing expiry time that is set by user.
=> feat: siwe - optional date params

package-lock.json, package.json, src/components/endpoints/Assets.vue, src/stores/index.ts
- Removing the deprecated package `@lukso/universalprofile-smart-contracts`.
[`@lukso/universalprofile-smart-contracts`](https://www.npmjs.com/package/@lukso/universalprofile-smart-contracts) was deprecated 4 months ago and replaced with [`@lukso/lsp-smart-contracts`](https://www.npmjs.com/package/@lukso/lsp-smart-contracts)
=> chore: remove deprecated package

vite.config.ts
Add support for require('buffer')
This will now return the buffer implementation from require('buffer')
but no longer assume or pollute the window globals. Similar things are
already happening to 'process/buffer'. I also had problems with vite dev
and some existing browser extension. Specifically LastPass for some odd reason.
=> feat: update vite config to add support for require('buffer')

src/compositions/useWalletConnect.ts
We started to have some issues and in particular @artkachenko has reached a request limit. After some investigation, I've found out that the previous bridge does work but on a slightly different domain - `https://safe-walletconnect.safe.global/`
I wasn't able to find any public announcements about that change of domain but opening `https://safe-walletconnect.gnosis.io` in the browser redirects to `https://safe-walletconnect.safe.global/`.
=> fix: changed wallet connect bridge

src/components/endpoints/SendLyx.vue
with current implementation, if you set a different address in the from input (different from the address that is injected in the page). When you click send, the address you set in the input will be replaced by the injected address.
Therefore, it is not possible to send a transaction from any address we want (to test the app). It is even confusing as we think we put a different address but it goes back to the default one.
This PR fixes that.
=> fix: fix from address of SendLyx component

package.json, src/components/endpoints/SendTransaction.vue
The `--write` command would silent the error and... write the diff. But bc is happens in the CI, it is not pushed to the repo. So it currently allow having non formatted files in the repo.
This fixes it.
Cf a working CI on a non formatted file:
https://github.com/lukso-network/universalprofile-test-dapp/actions/runs/3542186994
=> Test Fix prettier error

src/components/shared/ParamField.vue, src/helpers/config.ts, src/helpers/tokenUtils.ts
Return 0x when decoding an empty bytes
Point to test cfworker proxy
Display <undef> when unable to retrieve symbol and/or name for LSP7/LSP8
=> fix: Add cloudflare proxy and small misc fixes.

src/components/Connect.vue, src/components/endpoints/Accounts.vue, src/components/endpoints/GetNetworkId.vue, src/components/endpoints/SendTransaction.vue, src/components/shared/LSPSelect.vue, src/compositions/useErc725.ts, src/compositions/useLspFactory.ts, src/compositions/useWalletConnectV2.ts, src/compositions/useWeb3.ts, src/helpers/config.ts, src/helpers/customRequest.ts, src/helpers/localstorage.ts, src/helpers/tokenUtils.ts, src/utils/createLinks.ts, src/views/profile/Deploy.vue, src/views/profile/Detail.vue, src/views/profile/Upload.vue
_See the video of how it works below._
With #117 DApp began to use only test net for its internal requests like:
```typescript
const upOwner = await window.erc725Account.methods.owner().call()
```
This brings up quite a few issues for one simple reason - we can connect two applications that use different networks and that breaks everything. 
Example: when `erc725Account` is from L16 and DApp tries to use `methods.owner().call()` it expects the address of `erc725Account` to exist on `testnet` and sends requests to `testnet` RPC providers. From that line on everything stops working because there's no such address on `testnet`.
-----
Also, there are a few other bug fixes like:
- using `channel` instead of `isDesktop` for `sendRequest` function to decide how to send request;
- in …
=> feat: select network used by DApp

src/components/endpoints/SendTransaction.vue, src/components/endpoints/__tests__/SendTransaction.spec.ts
The user can still fill in transactions values, but a lot of the sample transactions require the value to be 0 making this confusing.
=> fix: Change to 0 value for sample transactions.

src/components/endpoints/SendTransaction.vue
Incorrect selector is computed when selecting `setData` in the list and the parameters are array
Fix it with the correct selector ✅
=> fix: replace selector by `setDataBatch`

src/compositions/useWeb3Connection.ts
Logging transaction hash once it's received as a response to eth_sendTransaction. 
It looks like this:
=> chore: logging transaction hash

src/compositions/useWeb3Connection.ts
Added logging of the request that's being sent to the extension.
One of the reasons is to get a quick sample of the payload that we can edit manually and trigger requests using `window.lukso.request`:
=> chore: logging the request that is about to be sent;

src/components/endpoints/GetNetworkId.vue
Adds base sepolia switching ability to test a dApp switching to base when base has no account in extension.
https://github.com/lukso-network/universalprofile-extension/pull/1354
https://app.clickup.com/t/2645698/DEV-11489
=> fix: adds base sepolia

src/helpers/functionUtils.ts
The issue: pasting ABI of encoded function may read and show invalid arguments in the UI.
The reason: last saved value stored in `signature-cache2`, which includes all decoded values of the last input, is returned if it matches the function selector of the given ABI.
Instead we should only take function signature from the cache if anything is found and then decode given ABI encoded function call.
Bug:
https://github.com/user-attachments/assets/f8a40b18-ad2e-45a7-bd12-80c8f6b4ecc8
Bug solved:
https://github.com/user-attachments/assets/a9760ecb-9dbb-427f-b969-76817dcda479
=> fix: ABI decoding should take place instead of random cache being returned

src/components/endpoints/ImportProfile.vue
Added a new flag for the up_import. 
Not enabling the check mark will not add that flag to the params of the request meaning up_import will still work as expected on current versions of the extension.
=> chore: added new flag to up_import - isDeviceToDeviceImport

package.json, yarn.lock
=> fix: Upgrade up-provider.

src/components/endpoints/Assets.vue, src/components/shared/ContractFunction.vue, src/components/shared/ParamField.vue, src/helpers/functionUtils.ts
Fixing logic of decoding data pasted into `transaction.data` field.
Issues:
- we have a cache with functions pulled from 4byte.directory. With those functions **we also keep decoded values of the pasted function call**. If you paste `execute(uint256,address,uint256,bytes)` encoded with smart contract deployment it will be saved into the cache with those arguments from the encoded smart contract deployment function. Pasting another `execute` ABI encoded payload will be replaced with that smart contract deployment arguments.
- updated function `makeBytes32` to support all size bytes. Now it's called `makeBytes`.
Example of the issue. See the first log with `props.data` - this is the pasted value.
Other logs have a new value that is immediately replaced the value pasted.
=> fix: transaction.data field bytes decoding
