- package.json
- yarn.lock
> fix: issue with fetching profiles

- src/components/Connect.vue
- src/components/__tests__/Connect.spec.ts
- src/components/endpoints/Accounts.vue
- src/components/endpoints/__tests__/Accounts.spec.ts
- src/compositions/useWalletConnect.ts
- src/compositions/useWeb3.ts
- src/stores/index.ts
- src/views/profile/send-lyx/__tests__/SendLyx.spec.ts
https://app.clickup.com/t/1ydf54a
> feat: chain details

- src/components/__tests__/Connect.spec.ts
- src/components/endpoints/Permissions.vue
- src/components/endpoints/SetData.vue
- src/components/endpoints/Sign.vue
- src/components/endpoints/__tests__/Accounts.spec.ts
- src/components/endpoints/__tests__/Permissions.spec.ts
- src/components/endpoints/__tests__/SetData.spec.ts
- src/components/endpoints/__tests__/Sign.ts
- src/helpers/config.ts
- src/stores/index.ts
- src/types.d.ts
https://app.clickup.com/t/251r1uy
> feat: validate signature

- src/components/endpoints/CustomRelayer.vue
- src/components/endpoints/__tests__/CustomRelayer.spec.ts
- src/views/Home.vue
Links: https://app.clickup.com/t/2tdm0ry
> feat: custom relayer card rpc which uses rpc call

- index.html
- jest.config.cjs
- jest.setup.cjs
- package-lock.json
- package.json
- src/components/Connect.vue
- src/components/endpoints/CustomRelayer.vue
- src/components/endpoints/Sign.vue
- src/components/endpoints/__tests__/CustomRelayer.spec.ts
- src/components/endpoints/__tests__/Sign.spec.ts
- src/utils/__tests__/dateTime.spec.ts
- src/utils/dateTime.ts
https://app.clickup.com/t/2t43mmc
Enhance Sign with SIWE.
CU-2t43mmc
> feat: sign in with ethereum

- src/components/endpoints/Sign.vue
- src/components/endpoints/__tests__/Sign.spec.ts
- src/utils/__tests__/dateTime.spec.ts
- src/utils/dateTime.ts
Add additional SIWE fields for debugging. Also fixed issue with default expiry date.
> feat: siwe additional fields

- src/components/endpoints/Sign.vue
https://app.clickup.com/t/2tfghry?comment=1074327367
> feat: cleanup empty resources

- src/components/endpoints/Sign.vue
https://app.clickup.com/t/2tt5dkb?comment=866581968
> fix: fix magic value check for SIWE

- package-lock.json
- package.json
- src/components/endpoints/ImportProfile.vue
- src/components/endpoints/Permissions.vue
- src/components/endpoints/SetData.vue
- src/components/endpoints/__tests__/Permissions.spec.ts
- src/components/endpoints/__tests__/SetData.spec.ts
- src/compositions/useWalletConnect.ts
https://app.clickup.com/t/2vzhzty
> fix: `encodeParameters` issue when calling `setData`

- package-lock.json
- package.json
This is also to trigger a new deployment and see if it fixes the GitHub page issue.
I tested locally with dev and build - everything works.
> Update typescript vite and vue-tsc

- package-lock.json
- package.json
- src/components/endpoints/Permissions.vue
https://app.clickup.com/t/2w55v0p
> fix: select all permissions omit SUPER_DELEGATECALL

- src/components/endpoints/GetNetId.vue
- src/views/Home.vue
This PR is adding a card to get the network ID using the Ethereum API instead of web3.js.
Internal ticket: https://app.clickup.com/t/2znnbyb
> feat: add network id card

- src/components/endpoints/Sign.vue
- src/components/endpoints/__tests__/Sign.spec.ts
- vite.config.ts
https://app.clickup.com/t/325p67e
- fixes URI in SIWE
- adjust sign response to signature only
> fix: sign changes

- src/compositions/useWalletConnect.ts
https://app.clickup.com/t/32001x8
CU-32001x8
> Change wc bridge link

- index.html
- src/components/Navbar.vue
- src/components/endpoints/Assets.vue
- src/components/endpoints/CustomRelayer.vue
- src/components/endpoints/GetNetworkId.vue
- src/components/endpoints/ImportProfile.vue
- src/components/endpoints/Permissions.vue
- src/components/endpoints/SendLyx.vue
- src/components/endpoints/SetData.vue
- src/components/endpoints/Sign.vue
- src/components/endpoints/__tests__/Permissions.spec.ts
- src/views/Home.vue
> Remove validation

- src/components/Connect.vue
- src/components/endpoints/CustomRelayer.vue
- src/components/endpoints/ImportProfile.vue
- src/compositions/useWalletConnect.ts
Added ability to send custom RPC through WalletConnect.
Before the update:
https://user-images.githubusercontent.com/36865532/200659029-0e57f8af-5fd1-4733-a849-9a747f60921c.mov
After the update (profile picker for custom relay service is not complete yet so don't mind it):
https://user-images.githubusercontent.com/36865532/200659062-35b055fa-6c9f-460f-b448-cb217fff38a7.mov
> feat: support for custom wallet connect requests

- src/components/endpoints/Assets.vue
LSP7 as token symbol name is confusing
> Replace LSP7 to MYT as default symbol name

- src/components/endpoints/Assets.vue
- src/components/endpoints/CustomRelayer.vue
- src/components/endpoints/GetNetworkId.vue
- src/components/endpoints/ImportProfile.vue
- src/components/endpoints/Mint.vue
- src/components/endpoints/Permissions.vue
- src/components/endpoints/SendLyx.vue
- src/components/endpoints/SetData.vue
- src/components/endpoints/Sign.vue
- src/components/endpoints/__tests__/Assets.spec.ts
- src/components/endpoints/__tests__/Mint.spec.ts
- src/stores/index.ts
- src/types.d.ts
- src/views/Home.vue
- fixes issue with proper wei amounts for mint and transfer
- reorganized mint to separate card
- load token address into mint/transfer after deploy
- improvement for notification so they now clear before triggering new action
> fix: token mint and transfer

- src/components/endpoints/Assets.vue
- src/components/endpoints/Mint.vue
- src/components/endpoints/Transfer.vue
- src/components/shared/CustomSelect.vue
- src/components/shared/Lsp4MetadataForm.vue
- src/compositions/useLspFactory.ts
- src/enums.ts
- src/types.d.ts
> feat: LSP8 compatibility (create, mint, transfer)

- src/components/endpoints/SendTransaction.vue
https://app.clickup.com/t/3wu7zxn
> feat: mock transfer ERC721 transactions

- src/components/endpoints/Assets.vue
When creating an LSP8 contract, the token ID type is set to 3
> feat: set tokenIdType value on lsp8 deployment

- src/components/shared/ContractFunction.vue
- src/components/shared/ParamField.vue
- src/helpers/functionUtils.ts
Improve and shortcut function validation.
> fix: Make the function detection is bit more versatile and shortcut booleans which are not 0 or 1.

- src/helpers/config.ts
> fix: Use production proxy

- README.md
- src/components/Connect.vue
- src/components/endpoints/Accounts.vue
- src/components/endpoints/__tests__/Accounts.spec.ts
- src/components/endpoints/__tests__/CustomRelayer.spec.ts
- src/compositions/__tests__/useLspFactory.spec.ts
- src/compositions/useLspFactory.ts
- src/compositions/useWalletConnectV2.ts
- src/global.d.ts
- src/helpers/config.ts
- src/helpers/customRequest.ts
Here are the issues that I was having with `window.ethereum` object: https://github.com/lukso-network/universalprofile-test-dapp/actions/runs/4231816391/jobs/7350792975
I suppose the error is the result of updated dependencies.
> fix: window.ethereum type issues - casting explicitly to any

- src/App.vue
- src/components/Navbar.vue
- src/compositions/useWeb3.ts
- src/router/index.ts
- src/views/IFrame.vue
Add a simple iframe to test first party iframe injection.
> fix: Add /iframe to test first party iframe

- src/components/endpoints/SendTransaction.vue
https://app.clickup.com/t/866a8kq2v
> fix: adds options

- src/components/endpoints/SendTransaction.vue
https://app.clickup.com/t/866abevnp
> fix: Adds operatorSend, operatorBurn, approve, safeTransferFrom

- src/components/endpoints/GetNetworkId.vue
- src/components/endpoints/SendTransaction.vue
- src/helpers/functionUtils.ts
https://app.clickup.com/t/2645698/DEV-5192
> feat: add network, change network, bug fixes

- src/components/Connect.vue
https://app.clickup.com/t/2645698/DEV-5163
> fix: disconnects after network switch

- src/components/shared/LSPSelect.vue
- src/helpers/config.ts
- src/stores/index.ts
https://app.clickup.com/t/2645698/DEV-8346
The test dApp has an exception during initialization due to LSP23 because it's still trying to
get the owner of the UP contract to get the keymanager. Since the keymanager is not required
this PR will just log and ignore the error.
> fix: Repair problems due to lsp23 and no keymanager

- src/components/endpoints/Mint.vue
- src/components/endpoints/__tests__/Mint.spec.ts
[DEV-2723](https://app.clickup.com/t/2645698/DEV-2723)
- fix issue when minting non divisible tokens
> fix: Fix when minting non divisible token

- package.json
- src/components/endpoints/Permissions.vue
- src/compositions/useErc725.ts
- src/helpers/tokenUtils.ts
- yarn.lock
Update permissions
Updates lsp smart contracts
Updates erc725
> fix: updates permissions, lsp-smart-contracts, erc725

- src/components/endpoints/ImportProfile.vue
https://app.clickup.com/t/2645698/DEV-8585
> feat: add up-recover

- package.json
- yarn.lock
Fixes SVG blocking/scaling issues on the bottom right corner.
- https://github.com/lukso-network/web3-onboard-config/pull/14
> Update web3-onboard library

- src/components/endpoints/SendTransaction.vue
> fix: updated function signatures for LSP7,LSP8

- src/components/endpoints/CustomRelayer.vue
- src/components/endpoints/GetNetworkId.vue
- src/components/endpoints/__tests__/CustomRelayer.spec.ts
- src/compositions/useWalletConnectV2.ts
- src/helpers/config.ts
- src/interfaces/network.d.ts
> fix(DEV-11410): remove l16 network

- src/components/endpoints/ImportProfile.vue
Reverts lukso-network/universalprofile-test-dapp#164
> Revert "chore: added new flag to up_import - isDeviceToDeviceImport"

- package.json
- yarn.lock
fix: Upgrade up-provider to 0.2.2
> fix: Upgrade up-provider to 0.2.2
